development:
      :address: smtp.gmail.com
      :port: 587
      :authentication: plain
      :user_name: martintamay9@gmail.com
      :password: newr0ad776
      :enable_starttls_auto: true
production:
      :address: smtp.gmail.com
      :port: 587
      :authentication: plain
      :user_name: martintamay9@gmail.com
      :password: newr0ad776
      :enable_starttls_auto: true